port: 7890
socks-port: 7891
mixed-port: 7892
ipv6: true
allow-lan: true
mode: rule
log-level: warning
external-controller: 0.0.0.0:9090
secret: "1234567890"

dns:
  enable: false


proxies:

  - name: "proxy1"
    type: vless
    server: 	
    port: 34455
    uuid: 
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: 
    reality-opts:
      public-key: 
    client-fingerprint: chrome # cannot be empty

  - name: "proxy2"
    type: hysteria
    server: 
    ports: 26700-28700
    auth_str: 
    alpn:
      - h3
    protocol: udp
    up: 9
    down: 99
    sni: apple.com
    skip-cert-verify: true
    recv_window_conn: 12845056
    recv_window: 51380224
    disable_mtu_discovery: true
    fast-open: true
    
  - name: "proxy3"
    type: socks5
    server: 127.0.0.1
    port: 7893    
    
proxy-groups:

- name: PROXY
  type: select
  proxies:
  - Auto - UrlTest
  - DIRECT
  - proxy1
  - proxy2
  - proxy3

- name: Auto - UrlTest
  type: url-test
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  proxies:
  - proxy1
  - proxy2
  - proxy3
     
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR6,::1/128,DIRECT,no-resolve
- IP-CIDR6,fc00::/7,DIRECT,no-resolve
- IP-CIDR6,fe80::/10,DIRECT,no-resolve
- IP-CIDR6,fd00::/8,DIRECT,no-resolve
- GEOSITE,gfw,PROXY
- GEOSITE,CN,DIRECT
- GEOIP,private,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
